name: Feature_scML
channels:
  - conda-forge
<<<<<<< HEAD
=======
  - bioconda
>>>>>>> 8bd37314557f03bbefbaf089a687d1810733c30f
  - defaults
dependencies:
  - python=3.7
  - numpy=1.20.1
  - pandas=1.2.4
  - scikit-learn=0.24.2
  - statsmodels=0.12.2
  - scipy
  - matplotlib
  - seaborn
<<<<<<< HEAD
  - pip
  - pip:
    - minepy==1.2.3
=======
  - minepy=1.2.3
  - pip
  - pip:
>>>>>>> 8bd37314557f03bbefbaf089a687d1810733c30f
    - mlxtend==0.18.0
    - statsmodels==0.12.2
    - skrebate==0.62
    - shap==0.39.0
